api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        multipart: ['application/merge-patch+json']
    swagger:
        versions: [3]
    allow_plain_identifiers: true