vich_uploader:
    db_driver: orm

    mappings:
        photo_de_profile:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
        photo_de_cinema:
            uri_prefix: /images/cinema
            upload_destination: '%kernel.project_dir%/public/images/cinema'
        photo_de_film:
            uri_prefix: /images/film
            upload_destination: '%kernel.project_dir%/public/images/film'
